
package org.esa.beam.ws.client;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "BeamWebService", targetNamespace = "http://www.brockmann-consult.de/ws/beam")
@XmlSeeAlso({
                    ObjectFactory.class
            })
public interface BeamWebService {


    /**
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns javax.activation.DataHandler
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "pixels", targetNamespace = "")
    @RequestWrapper(localName = "readPixelsFloat", targetNamespace = "http://www.brockmann-consult.de/ws/beam", className = "org.esa.beam.ws.client.ReadPixelsFloat")
    @ResponseWrapper(localName = "readPixelsFloatResponse", targetNamespace = "http://www.brockmann-consult.de/ws/beam", className = "org.esa.beam.ws.client.ReadPixelsFloatResponse")
    @Action(input = "http://www.brockmann-consult.de/ws/beam/BeamWebService/readPixelsFloatRequest", output = "http://www.brockmann-consult.de/ws/beam/BeamWebService/readPixelsFloatResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://www.brockmann-consult.de/ws/beam/BeamWebService/readPixelsFloat/Fault/IOException")
    })
    public DataHandler readPixelsFloat(
            @WebParam(name = "arg0", targetNamespace = "")
            ProductId arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            int arg2,
            @WebParam(name = "arg3", targetNamespace = "")
            int arg3,
            @WebParam(name = "arg4", targetNamespace = "")
            int arg4,
            @WebParam(name = "arg5", targetNamespace = "")
            int arg5)
            throws IOException_Exception
    ;

    /**
     * @param w
     * @param bandName
     * @param h
     * @param y
     * @param x
     * @param productId
     * @return returns javax.activation.DataHandler
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "pixels", targetNamespace = "")
    @RequestWrapper(localName = "readPixelsInt", targetNamespace = "http://www.brockmann-consult.de/ws/beam", className = "org.esa.beam.ws.client.ReadPixelsInt")
    @ResponseWrapper(localName = "readPixelsIntResponse", targetNamespace = "http://www.brockmann-consult.de/ws/beam", className = "org.esa.beam.ws.client.ReadPixelsIntResponse")
    @Action(input = "http://www.brockmann-consult.de/ws/beam/BeamWebService/readPixelsIntRequest", output = "http://www.brockmann-consult.de/ws/beam/BeamWebService/readPixelsIntResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://www.brockmann-consult.de/ws/beam/BeamWebService/readPixelsInt/Fault/IOException")
    })
    public DataHandler readPixelsInt(
            @WebParam(name = "productId", targetNamespace = "")
            ProductId productId,
            @WebParam(name = "bandName", targetNamespace = "")
            String bandName,
            @WebParam(name = "x", targetNamespace = "")
            int x,
            @WebParam(name = "y", targetNamespace = "")
            int y,
            @WebParam(name = "w", targetNamespace = "")
            int w,
            @WebParam(name = "h", targetNamespace = "")
            int h)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns org.esa.beam.ws.client.ProductId
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "openProduct", targetNamespace = "http://www.brockmann-consult.de/ws/beam", className = "org.esa.beam.ws.client.OpenProduct")
    @ResponseWrapper(localName = "openProductResponse", targetNamespace = "http://www.brockmann-consult.de/ws/beam", className = "org.esa.beam.ws.client.OpenProductResponse")
    @Action(input = "http://www.brockmann-consult.de/ws/beam/BeamWebService/openProductRequest", output = "http://www.brockmann-consult.de/ws/beam/BeamWebService/openProductResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://www.brockmann-consult.de/ws/beam/BeamWebService/openProduct/Fault/IOException")
    })
    public ProductId openProduct(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "closeProduct", targetNamespace = "http://www.brockmann-consult.de/ws/beam", className = "org.esa.beam.ws.client.CloseProduct")
    @ResponseWrapper(localName = "closeProductResponse", targetNamespace = "http://www.brockmann-consult.de/ws/beam", className = "org.esa.beam.ws.client.CloseProductResponse")
    @Action(input = "http://www.brockmann-consult.de/ws/beam/BeamWebService/closeProductRequest", output = "http://www.brockmann-consult.de/ws/beam/BeamWebService/closeProductResponse", fault = {
            @FaultAction(className = IOException_Exception.class, value = "http://www.brockmann-consult.de/ws/beam/BeamWebService/closeProduct/Fault/IOException")
    })
    public void closeProduct(
            @WebParam(name = "arg0", targetNamespace = "")
            ProductId arg0)
            throws IOException_Exception
    ;

    /**
     * @param arg0
     * @return returns java.util.List<org.esa.beam.ws.client.BandId>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBands", targetNamespace = "http://www.brockmann-consult.de/ws/beam", className = "org.esa.beam.ws.client.GetBands")
    @ResponseWrapper(localName = "getBandsResponse", targetNamespace = "http://www.brockmann-consult.de/ws/beam", className = "org.esa.beam.ws.client.GetBandsResponse")
    @Action(input = "http://www.brockmann-consult.de/ws/beam/BeamWebService/getBandsRequest", output = "http://www.brockmann-consult.de/ws/beam/BeamWebService/getBandsResponse")
    public List<BandId> getBands(
            @WebParam(name = "arg0", targetNamespace = "")
            ProductId arg0);

}
